--------------------------------------------------------
-- HOSPITAL MANAGEMENT SYSTEM (HMS)
-- Oracle SQL Developer Schema Creation
-- Database: SCHEMA_PROJECT
-- 
-- Features:
-- - Complete normalized database (3NF)
-- - All tables with constraints and foreign keys
-- - Role-based access: Admin, Doctor, Patient
-- - No CLOB in GROUP BY issues
-- - Oracle-optimized syntax
--------------------------------------------------------

-- ============================================
-- SECTION 1: CLEANUP
-- ============================================

-- Drop all existing tables in reverse dependency order
BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables WHERE table_name LIKE 'HIS_%') LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- Drop sequences if they exist
BEGIN
   FOR cur_rec IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'HIS_%') LOOP
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || cur_rec.sequence_name;
   END LOOP;
END;
/

-- Drop views if they exist
BEGIN
   FOR cur_rec IN (SELECT view_name FROM user_views WHERE view_name LIKE 'V_%') LOOP
      EXECUTE IMMEDIATE 'DROP VIEW ' || cur_rec.view_name;
   END LOOP;
END;
/

-- Set date format for Oracle
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-- ============================================
-- SECTION 2: CREATE SEQUENCES
-- ============================================

CREATE SEQUENCE HIS_ADMIN_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_VENDOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_DOCS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_PATIENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_PHARM_CAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_PHARM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_ACCOUNTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_ASSETS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_EQUIPMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_LAB_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_MEDICAL_REC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_TRANSFER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_PAYROLL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_PRESCRIPTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_PWDRESET_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_SURGERY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_VITALS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_ROLES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_PRIVILEGES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_ROLE_PRIV_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HIS_USER_ROLES_SEQ START WITH 1 INCREMENT BY 1;

-- ============================================
-- SECTION 3: INDEPENDENT CORE TABLES
-- ============================================

-- --------------------------------------------
-- TABLE: HIS_ADMIN
-- Purpose: Hospital administrators
-- Normalized: 3NF
-- --------------------------------------------
CREATE TABLE HIS_ADMIN (
    AD_ID NUMBER PRIMARY KEY,
    AD_FNAME VARCHAR2(200) NOT NULL,
    AD_LNAME VARCHAR2(200) NOT NULL,
    AD_EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    AD_PWD VARCHAR2(200) NOT NULL,
    AD_DPIC VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_AD_EMAIL CHECK (AD_EMAIL LIKE '%@%.%'),
    CONSTRAINT CHK_AD_FNAME CHECK (LENGTH(AD_FNAME) >= 1),
    CONSTRAINT CHK_AD_LNAME CHECK (LENGTH(AD_LNAME) >= 1)
);

CREATE OR REPLACE TRIGGER HIS_ADMIN_TRG
BEFORE INSERT ON HIS_ADMIN
FOR EACH ROW
BEGIN
    IF :NEW.AD_ID IS NULL THEN
        SELECT HIS_ADMIN_SEQ.NEXTVAL INTO :NEW.AD_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_VENDOR
-- Purpose: Medical suppliers and vendors
-- Normalized: 3NF
-- --------------------------------------------
CREATE TABLE HIS_VENDOR (
    V_ID NUMBER PRIMARY KEY,
    V_NUMBER VARCHAR2(200) UNIQUE,
    V_NAME VARCHAR2(200) NOT NULL UNIQUE,
    V_ADR VARCHAR2(500),
    V_MOBILE VARCHAR2(200),
    V_EMAIL VARCHAR2(200),
    V_PHONE VARCHAR2(200),
    V_DESC VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_V_EMAIL CHECK (V_EMAIL LIKE '%@%.%'),
    CONSTRAINT CHK_V_NAME_LENGTH CHECK (LENGTH(V_NAME) >= 2)
);

CREATE OR REPLACE TRIGGER HIS_VENDOR_TRG
BEFORE INSERT ON HIS_VENDOR
FOR EACH ROW
BEGIN
    IF :NEW.V_ID IS NULL THEN
        SELECT HIS_VENDOR_SEQ.NEXTVAL INTO :NEW.V_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_DOCS
-- Purpose: Doctors and medical staff
-- Normalized: 3NF
-- --------------------------------------------
CREATE TABLE HIS_DOCS (
    DOC_ID NUMBER PRIMARY KEY,
    DOC_FNAME VARCHAR2(200) NOT NULL,
    DOC_LNAME VARCHAR2(200) NOT NULL,
    DOC_EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    DOC_PWD VARCHAR2(200) NOT NULL,
    DOC_DEPT VARCHAR2(200),
    DOC_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    DOC_DPIC VARCHAR2(200),
    DOC_SPECIALIZATION VARCHAR2(200),
    DOC_PHONE VARCHAR2(200),
    DOC_STATUS VARCHAR2(50) DEFAULT 'Active',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_DOC_STATUS CHECK (DOC_STATUS IN ('Active', 'Inactive', 'On Leave')),
    CONSTRAINT CHK_DOC_EMAIL CHECK (DOC_EMAIL LIKE '%@%.%')
);

CREATE OR REPLACE TRIGGER HIS_DOCS_TRG
BEFORE INSERT ON HIS_DOCS
FOR EACH ROW
BEGIN
    IF :NEW.DOC_ID IS NULL THEN
        SELECT HIS_DOCS_SEQ.NEXTVAL INTO :NEW.DOC_ID FROM DUAL;
    END IF;
END;
/

-- ============================================
-- SECTION 4: DEPENDENT TABLES WITH FOREIGN KEYS
-- ============================================

-- --------------------------------------------
-- TABLE: HIS_PATIENTS
-- Purpose: Patient records
-- Normalized: 3NF
-- Foreign Key: PAT_ASSIGNED_DOC -> HIS_DOCS.DOC_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_PATIENTS (
    PAT_ID NUMBER PRIMARY KEY,
    PAT_FNAME VARCHAR2(200) NOT NULL,
    PAT_LNAME VARCHAR2(200) NOT NULL,
    PAT_DOB DATE,
    PAT_AGE NUMBER,
    PAT_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    PAT_ADDR VARCHAR2(500),
    PAT_PHONE VARCHAR2(200),
    PAT_EMAIL VARCHAR2(200),
    PAT_PWD VARCHAR2(255),
    PAT_TYPE VARCHAR2(50),
    PAT_ASSIGNED_DOC VARCHAR2(200),
    PAT_DATE_JOINED TIMESTAMP DEFAULT SYSTIMESTAMP,
    PAT_AILMENT VARCHAR2(500),
    PAT_DISCHARGE_STATUS VARCHAR2(50),
    PAT_GENDER VARCHAR2(20),
    PAT_BLOOD_GROUP VARCHAR2(10),
    PAT_EMERGENCY_CONTACT VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_PAT_TYPE CHECK (PAT_TYPE IN ('InPatient', 'OutPatient')),
    CONSTRAINT CHK_PAT_GENDER CHECK (PAT_GENDER IN ('Male', 'Female', 'Other')),
    CONSTRAINT CHK_PAT_AGE CHECK (PAT_AGE >= 0 AND PAT_AGE <= 150),
    CONSTRAINT FK_PAT_DOC FOREIGN KEY (PAT_ASSIGNED_DOC) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL
);

CREATE OR REPLACE TRIGGER HIS_PATIENTS_TRG
BEFORE INSERT ON HIS_PATIENTS
FOR EACH ROW
BEGIN
    IF :NEW.PAT_ID IS NULL THEN
        SELECT HIS_PATIENTS_SEQ.NEXTVAL INTO :NEW.PAT_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_PHARMACEUTICALS_CATEGORIES
-- Purpose: Medicine categories
-- Normalized: 3NF
-- --------------------------------------------
CREATE TABLE HIS_PHARMACEUTICALS_CATEGORIES (
    PHARM_CAT_ID NUMBER PRIMARY KEY,
    PHARM_CAT_NAME VARCHAR2(200) NOT NULL UNIQUE,
    PHARM_CAT_VENDOR VARCHAR2(200),
    PHARM_CAT_DESC VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER HIS_PHARM_CAT_TRG
BEFORE INSERT ON HIS_PHARMACEUTICALS_CATEGORIES
FOR EACH ROW
BEGIN
    IF :NEW.PHARM_CAT_ID IS NULL THEN
        SELECT HIS_PHARM_CAT_SEQ.NEXTVAL INTO :NEW.PHARM_CAT_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_PHARMACEUTICALS
-- Purpose: Medicine inventory
-- Normalized: 3NF
-- Foreign Keys: PHAR_VENDOR, PHAR_CAT
-- --------------------------------------------
CREATE TABLE HIS_PHARMACEUTICALS (
    PHAR_ID NUMBER PRIMARY KEY,
    PHAR_NAME VARCHAR2(200) NOT NULL,
    PHAR_BCODE VARCHAR2(200) UNIQUE,
    PHAR_DESC VARCHAR2(1000),
    PHAR_QTY NUMBER DEFAULT 0,
    PHAR_UNIT_PRICE NUMBER(10,2),
    PHAR_CAT VARCHAR2(200),
    PHAR_VENDOR VARCHAR2(200),
    PHAR_EXPIRY_DATE DATE,
    PHAR_MANUFACTURING_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PHAR_VENDOR FOREIGN KEY (PHAR_VENDOR) 
        REFERENCES HIS_VENDOR(V_NAME) ON DELETE SET NULL,
    CONSTRAINT FK_PHAR_CAT FOREIGN KEY (PHAR_CAT) 
        REFERENCES HIS_PHARMACEUTICALS_CATEGORIES(PHARM_CAT_NAME) ON DELETE SET NULL,
    CONSTRAINT CHK_PHAR_QTY CHECK (PHAR_QTY >= 0),
    CONSTRAINT CHK_PHAR_PRICE CHECK (PHAR_UNIT_PRICE >= 0),
    CONSTRAINT CHK_PHAR_DATES CHECK (PHAR_EXPIRY_DATE > PHAR_MANUFACTURING_DATE)
);

CREATE OR REPLACE TRIGGER HIS_PHARM_TRG
BEFORE INSERT ON HIS_PHARMACEUTICALS
FOR EACH ROW
BEGIN
    IF :NEW.PHAR_ID IS NULL THEN
        SELECT HIS_PHARM_SEQ.NEXTVAL INTO :NEW.PHAR_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_ACCOUNTS
-- Purpose: Financial accounts
-- Normalized: 3NF
-- --------------------------------------------
CREATE TABLE HIS_ACCOUNTS (
    ACC_ID NUMBER PRIMARY KEY,
    ACC_NAME VARCHAR2(200) NOT NULL,
    ACC_DESC VARCHAR2(1000),
    ACC_TYPE VARCHAR2(100),
    ACC_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    ACC_AMOUNT NUMBER(15,2) DEFAULT 0,
    ACC_CURRENCY VARCHAR2(10) DEFAULT 'USD',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_ACC_TYPE CHECK (ACC_TYPE IN ('Payable Account', 'Receivable Account', 'Asset Account', 'Liability Account', 'Equity Account')),
    CONSTRAINT CHK_ACC_CURRENCY CHECK (ACC_CURRENCY IN ('USD', 'EUR', 'GBP', 'INR'))
);

CREATE OR REPLACE TRIGGER HIS_ACCOUNTS_TRG
BEFORE INSERT ON HIS_ACCOUNTS
FOR EACH ROW
BEGIN
    IF :NEW.ACC_ID IS NULL THEN
        SELECT HIS_ACCOUNTS_SEQ.NEXTVAL INTO :NEW.ACC_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_ASSETS
-- Purpose: Hospital assets
-- Normalized: 3NF
-- Foreign Key: ASST_VENDOR
-- --------------------------------------------
CREATE TABLE HIS_ASSETS (
    ASST_ID NUMBER PRIMARY KEY,
    ASST_NAME VARCHAR2(200) NOT NULL,
    ASST_DESC VARCHAR2(1000),
    ASST_VENDOR VARCHAR2(200),
    ASST_STATUS VARCHAR2(50) DEFAULT 'Active',
    ASST_DEPT VARCHAR2(200),
    ASST_PURCHASE_DATE DATE,
    ASST_PURCHASE_COST NUMBER(12,2),
    ASST_SERIAL_NUMBER VARCHAR2(200) UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ASST_VENDOR FOREIGN KEY (ASST_VENDOR) 
        REFERENCES HIS_VENDOR(V_NAME) ON DELETE SET NULL,
    CONSTRAINT CHK_ASST_STATUS CHECK (ASST_STATUS IN ('Active', 'Maintenance', 'Retired', 'Broken')),
    CONSTRAINT CHK_ASST_COST CHECK (ASST_PURCHASE_COST >= 0)
);

CREATE OR REPLACE TRIGGER HIS_ASSETS_TRG
BEFORE INSERT ON HIS_ASSETS
FOR EACH ROW
BEGIN
    IF :NEW.ASST_ID IS NULL THEN
        SELECT HIS_ASSETS_SEQ.NEXTVAL INTO :NEW.ASST_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_EQUIPMENTS
-- Purpose: Medical equipment
-- Normalized: 3NF
-- Foreign Key: EQP_VENDOR
-- --------------------------------------------
CREATE TABLE HIS_EQUIPMENTS (
    EQP_ID NUMBER PRIMARY KEY,
    EQP_CODE VARCHAR2(200) UNIQUE,
    EQP_NAME VARCHAR2(200) NOT NULL,
    EQP_VENDOR VARCHAR2(200),
    EQP_DESC VARCHAR2(1000),
    EQP_DEPT VARCHAR2(200),
    EQP_STATUS VARCHAR2(50) DEFAULT 'Functioning',
    EQP_QTY NUMBER DEFAULT 0,
    EQP_LOCATION VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EQP_VENDOR FOREIGN KEY (EQP_VENDOR) 
        REFERENCES HIS_VENDOR(V_NAME) ON DELETE SET NULL,
    CONSTRAINT CHK_EQP_STATUS CHECK (EQP_STATUS IN ('Functioning', 'Under Repair', 'Out of Service', 'Reserved')),
    CONSTRAINT CHK_EQP_QTY CHECK (EQP_QTY >= 0)
);

CREATE OR REPLACE TRIGGER HIS_EQUIPMENT_TRG
BEFORE INSERT ON HIS_EQUIPMENTS
FOR EACH ROW
BEGIN
    IF :NEW.EQP_ID IS NULL THEN
        SELECT HIS_EQUIPMENT_SEQ.NEXTVAL INTO :NEW.EQP_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_LABORATORY
-- Purpose: Laboratory tests
-- Normalized: 3NF
-- Foreign Keys: LAB_PAT_NUMBER, LAB_DOC_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_LABORATORY (
    LAB_ID NUMBER PRIMARY KEY,
    LAB_PAT_NAME VARCHAR2(200),
    LAB_PAT_AILMENT VARCHAR2(500),
    LAB_PAT_NUMBER VARCHAR2(200) NOT NULL,
    LAB_DOC_NUMBER VARCHAR2(200),
    LAB_PAT_TESTS VARCHAR2(1000),
    LAB_PAT_RESULTS VARCHAR2(2000),
    LAB_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    LAB_STATUS VARCHAR2(50) DEFAULT 'Pending',
    LAB_DATE_REC TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAB_COMPLETED_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LAB_PAT FOREIGN KEY (LAB_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_LAB_DOC FOREIGN KEY (LAB_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_LAB_STATUS CHECK (LAB_STATUS IN ('Pending', 'In Progress', 'Completed', 'Cancelled'))
);

CREATE OR REPLACE TRIGGER HIS_LAB_TRG
BEFORE INSERT ON HIS_LABORATORY
FOR EACH ROW
BEGIN
    IF :NEW.LAB_ID IS NULL THEN
        SELECT HIS_LAB_SEQ.NEXTVAL INTO :NEW.LAB_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_MEDICAL_RECORDS
-- Purpose: Patient medical records
-- Normalized: 3NF
-- Foreign Keys: MDR_PAT_NUMBER, MDR_DOC_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_MEDICAL_RECORDS (
    MDR_ID NUMBER PRIMARY KEY,
    MDR_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    MDR_PAT_NAME VARCHAR2(200),
    MDR_PAT_ADR VARCHAR2(500),
    MDR_PAT_AGE NUMBER,
    MDR_PAT_AILMENT VARCHAR2(500),
    MDR_PAT_NUMBER VARCHAR2(200) NOT NULL,
    MDR_DOC_NUMBER VARCHAR2(200),
    MDR_PAT_PRESCR VARCHAR2(2000),
    MDR_DIAGNOSIS VARCHAR2(1000),
    MDR_TREATMENT_PLAN VARCHAR2(2000),
    MDR_DATE_REC TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_MDR_PAT FOREIGN KEY (MDR_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_MDR_DOC FOREIGN KEY (MDR_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL
);

CREATE OR REPLACE TRIGGER HIS_MEDICAL_REC_TRG
BEFORE INSERT ON HIS_MEDICAL_RECORDS
FOR EACH ROW
BEGIN
    IF :NEW.MDR_ID IS NULL THEN
        SELECT HIS_MEDICAL_REC_SEQ.NEXTVAL INTO :NEW.MDR_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_PATIENT_TRANSFER
-- Purpose: Patient transfers
-- Foreign Key: PT_PAT_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_PATIENT_TRANSFER (
    PT_ID NUMBER PRIMARY KEY,
    PT_PAT_NUMBER VARCHAR2(200),
    PT_PAT_NAME VARCHAR2(200),
    PT_FROM_WARD VARCHAR2(200),
    PT_TO_WARD VARCHAR2(200),
    PT_REASON VARCHAR2(1000),
    PT_TRANSFER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    PT_AUTHORIZED_BY VARCHAR2(200),
    PT_STATUS VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_TRANSFER_PAT FOREIGN KEY (PT_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_TRANSFER_STATUS CHECK (PT_STATUS IN ('Pending', 'Completed', 'Cancelled'))
);

CREATE OR REPLACE TRIGGER HIS_TRANSFER_TRG
BEFORE INSERT ON HIS_PATIENT_TRANSFER
FOR EACH ROW
BEGIN
    IF :NEW.PT_ID IS NULL THEN
        SELECT HIS_TRANSFER_SEQ.NEXTVAL INTO :NEW.PT_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_PAYROLLS
-- Purpose: Employee payroll
-- Foreign Key: PAY_DOC_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_PAYROLLS (
    PAY_ID NUMBER PRIMARY KEY,
    PAY_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    PAY_DOC_NUMBER VARCHAR2(200) NOT NULL,
    PAY_DOC_NAME VARCHAR2(200),
    PAY_DOC_EMAIL VARCHAR2(200),
    PAY_AMOUNT NUMBER(12,2),
    PAY_PERIOD VARCHAR2(100),
    PAY_STATUS VARCHAR2(50) DEFAULT 'Pending',
    PAY_DATE DATE,
    PAY_METHOD VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PAY_DOC FOREIGN KEY (PAY_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE CASCADE,
    CONSTRAINT CHK_PAY_STATUS CHECK (PAY_STATUS IN ('Pending', 'Paid', 'Cancelled', 'On Hold')),
    CONSTRAINT CHK_PAY_METHOD CHECK (PAY_METHOD IN ('Bank Transfer', 'Check', 'Cash', 'Direct Deposit')),
    CONSTRAINT CHK_PAY_AMOUNT CHECK (PAY_AMOUNT > 0)
);

CREATE OR REPLACE TRIGGER HIS_PAYROLL_TRG
BEFORE INSERT ON HIS_PAYROLLS
FOR EACH ROW
BEGIN
    IF :NEW.PAY_ID IS NULL THEN
        SELECT HIS_PAYROLL_SEQ.NEXTVAL INTO :NEW.PAY_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_PRESCRIPTIONS
-- Purpose: Medical prescriptions
-- Normalized: 3NF
-- Foreign Keys: PRES_PAT_NUMBER, PRES_DOC_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_PRESCRIPTIONS (
    PRES_ID NUMBER PRIMARY KEY,
    PRES_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    PRES_PAT_NUMBER VARCHAR2(200) NOT NULL,
    PRES_PAT_NAME VARCHAR2(200),
    PRES_DOC_NUMBER VARCHAR2(200),
    PRES_DOC_NAME VARCHAR2(200),
    PRES_MEDICATION VARCHAR2(500),
    PRES_DOSAGE VARCHAR2(200),
    PRES_FREQUENCY VARCHAR2(200),
    PRES_DURATION VARCHAR2(200),
    PRES_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRES_STATUS VARCHAR2(50) DEFAULT 'Active',
    PRES_REFILLS_REMAINING NUMBER DEFAULT 0,
    PRES_NOTES VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PRES_PAT FOREIGN KEY (PRES_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_PRES_DOC FOREIGN KEY (PRES_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_PRES_STATUS CHECK (PRES_STATUS IN ('Active', 'Completed', 'Cancelled', 'Expired'))
);

CREATE OR REPLACE TRIGGER HIS_PRESCRIPTION_TRG
BEFORE INSERT ON HIS_PRESCRIPTIONS
FOR EACH ROW
BEGIN
    IF :NEW.PRES_ID IS NULL THEN
        SELECT HIS_PRESCRIPTION_SEQ.NEXTVAL INTO :NEW.PRES_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_PWDRESETS
-- Purpose: Password reset tokens
-- --------------------------------------------
CREATE TABLE HIS_PWDRESETS (
    ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(200) NOT NULL,
    RESET_TOKEN VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRES_AT TIMESTAMP
);

CREATE OR REPLACE TRIGGER HIS_PWDRESET_TRG
BEFORE INSERT ON HIS_PWDRESETS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT HIS_PWDRESET_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_SURGERY
-- Purpose: Surgery records
-- Foreign Keys: SURG_PAT_NUMBER, SURG_DOC_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_SURGERY (
    SURG_ID NUMBER PRIMARY KEY,
    SURG_NUMBER VARCHAR2(200) NOT NULL UNIQUE,
    SURG_PAT_NUMBER VARCHAR2(200) NOT NULL,
    SURG_PAT_NAME VARCHAR2(200),
    SURG_DOC_NUMBER VARCHAR2(200),
    SURG_DOC_NAME VARCHAR2(200),
    SURG_TYPE VARCHAR2(200),
    SURG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    SURG_DURATION VARCHAR2(100),
    SURG_STATUS VARCHAR2(50),
    SURG_NOTES VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_SURG_PAT FOREIGN KEY (SURG_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT FK_SURG_DOC FOREIGN KEY (SURG_DOC_NUMBER) 
        REFERENCES HIS_DOCS(DOC_NUMBER) ON DELETE SET NULL,
    CONSTRAINT CHK_SURG_STATUS CHECK (SURG_STATUS IN ('Scheduled', 'In Progress', 'Completed', 'Cancelled'))
);

CREATE OR REPLACE TRIGGER HIS_SURGERY_TRG
BEFORE INSERT ON HIS_SURGERY
FOR EACH ROW
BEGIN
    IF :NEW.SURG_ID IS NULL THEN
        SELECT HIS_SURGERY_SEQ.NEXTVAL INTO :NEW.SURG_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_VITALS
-- Purpose: Patient vital signs
-- Foreign Keys: VIT_PAT_NUMBER
-- --------------------------------------------
CREATE TABLE HIS_VITALS (
    VIT_ID NUMBER PRIMARY KEY,
    VIT_PAT_NUMBER VARCHAR2(200) NOT NULL,
    VIT_PAT_NAME VARCHAR2(200),
    VIT_BODYTEMP NUMBER(5,2),
    VIT_HEARTPULSE NUMBER,
    VIT_RESPIRATION NUMBER,
    VIT_WEIGHT NUMBER(6,2),
    VIT_BLOOD_PRESSURE VARCHAR2(20),
    VIT_OXYGEN_SAT NUMBER(5,2),
    VIT_RECORDED_BY VARCHAR2(200),
    VIT_RECORDED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_VIT_PAT FOREIGN KEY (VIT_PAT_NUMBER) 
        REFERENCES HIS_PATIENTS(PAT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT CHK_VIT_TEMP CHECK (VIT_BODYTEMP BETWEEN 90 AND 110),
    CONSTRAINT CHK_VIT_PULSE CHECK (VIT_HEARTPULSE BETWEEN 30 AND 220),
    CONSTRAINT CHK_VIT_RESP CHECK (VIT_RESPIRATION BETWEEN 5 AND 60),
    CONSTRAINT CHK_VIT_WEIGHT CHECK (VIT_WEIGHT > 0),
    CONSTRAINT CHK_VIT_O2 CHECK (VIT_OXYGEN_SAT BETWEEN 0 AND 100)
);

CREATE OR REPLACE TRIGGER HIS_VITALS_TRG
BEFORE INSERT ON HIS_VITALS
FOR EACH ROW
BEGIN
    IF :NEW.VIT_ID IS NULL THEN
        SELECT HIS_VITALS_SEQ.NEXTVAL INTO :NEW.VIT_ID FROM DUAL;
    END IF;
END;
/

-- ============================================
-- SECTION 5: USER AND ROLE MANAGEMENT
-- ============================================

-- --------------------------------------------
-- TABLE: HIS_ROLES
-- Purpose: User roles (Admin, Doctor, Patient)
-- --------------------------------------------
CREATE TABLE HIS_ROLES (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(100) NOT NULL UNIQUE,
    ROLE_DESC VARCHAR2(1000),
    ROLE_LEVEL NUMBER DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_ROLE_LEVEL CHECK (ROLE_LEVEL BETWEEN 1 AND 10),
    CONSTRAINT CHK_ROLE_NAME CHECK (LENGTH(ROLE_NAME) >= 2)
);

CREATE OR REPLACE TRIGGER HIS_ROLES_TRG
BEFORE INSERT ON HIS_ROLES
FOR EACH ROW
BEGIN
    IF :NEW.ROLE_ID IS NULL THEN
        SELECT HIS_ROLES_SEQ.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_PRIVILEGES
-- Purpose: System privileges
-- --------------------------------------------
CREATE TABLE HIS_PRIVILEGES (
    PRIV_ID NUMBER PRIMARY KEY,
    PRIV_NAME VARCHAR2(100) NOT NULL UNIQUE,
    PRIV_DESC VARCHAR2(1000),
    PRIV_MODULE VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER HIS_PRIVILEGES_TRG
BEFORE INSERT ON HIS_PRIVILEGES
FOR EACH ROW
BEGIN
    IF :NEW.PRIV_ID IS NULL THEN
        SELECT HIS_PRIVILEGES_SEQ.NEXTVAL INTO :NEW.PRIV_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_ROLE_PRIVILEGES
-- Purpose: Role-Privilege mapping
-- --------------------------------------------
CREATE TABLE HIS_ROLE_PRIVILEGES (
    RP_ID NUMBER PRIMARY KEY,
    ROLE_ID NUMBER NOT NULL,
    PRIV_ID NUMBER NOT NULL,
    GRANTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    GRANTED_BY VARCHAR2(200),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) 
        REFERENCES HIS_ROLES(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PRIV FOREIGN KEY (PRIV_ID) 
        REFERENCES HIS_PRIVILEGES(PRIV_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_ROLE_PRIV UNIQUE (ROLE_ID, PRIV_ID)
);

CREATE OR REPLACE TRIGGER HIS_ROLE_PRIV_TRG
BEFORE INSERT ON HIS_ROLE_PRIVILEGES
FOR EACH ROW
BEGIN
    IF :NEW.RP_ID IS NULL THEN
        SELECT HIS_ROLE_PRIV_SEQ.NEXTVAL INTO :NEW.RP_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_USERS
-- Purpose: Unified user accounts
-- --------------------------------------------
CREATE TABLE HIS_USERS (
    USER_ID NUMBER PRIMARY KEY,
    USER_EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(200) NOT NULL,
    USER_ROLE_ID NUMBER,
    USER_FNAME VARCHAR2(200) NOT NULL,
    USER_LNAME VARCHAR2(200) NOT NULL,
    USER_STATUS VARCHAR2(50) DEFAULT 'Active',
    USER_LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ROLE_ID) 
        REFERENCES HIS_ROLES(ROLE_ID) ON DELETE SET NULL,
    CONSTRAINT CHK_USER_STATUS CHECK (USER_STATUS IN ('Active', 'Inactive', 'Suspended', 'Locked')),
    CONSTRAINT CHK_USER_EMAIL CHECK (USER_EMAIL LIKE '%@%.%')
);

CREATE OR REPLACE TRIGGER HIS_USERS_TRG
BEFORE INSERT ON HIS_USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT HIS_USERS_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
END;
/

-- --------------------------------------------
-- TABLE: HIS_USER_ROLES
-- Purpose: User-Role mapping
-- --------------------------------------------
CREATE TABLE HIS_USER_ROLES (
    UR_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    ASSIGNED_BY VARCHAR2(200),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) 
        REFERENCES HIS_USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) 
        REFERENCES HIS_ROLES(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

CREATE OR REPLACE TRIGGER HIS_USER_ROLES_TRG
BEFORE INSERT ON HIS_USER_ROLES
FOR EACH ROW
BEGIN
    IF :NEW.UR_ID IS NULL THEN
        SELECT HIS_USER_ROLES_SEQ.NEXTVAL INTO :NEW.UR_ID FROM DUAL;
    END IF;
END;
/

-- ============================================
-- SECTION 6: PERFORMANCE INDEXES
-- ============================================
-- Note: UNIQUE constraints automatically create indexes
-- Only creating indexes on non-unique columns

-- CREATE INDEX IDX_PAT_NUMBER ON HIS_PATIENTS(PAT_NUMBER); -- Already indexed via UNIQUE constraint
CREATE INDEX IDX_PAT_ASSIGNED_DOC ON HIS_PATIENTS(PAT_ASSIGNED_DOC);
CREATE INDEX IDX_PAT_TYPE ON HIS_PATIENTS(PAT_TYPE);
-- CREATE INDEX IDX_DOC_NUMBER ON HIS_DOCS(DOC_NUMBER); -- Already indexed via UNIQUE constraint
-- CREATE INDEX IDX_DOC_EMAIL ON HIS_DOCS(DOC_EMAIL); -- Already indexed via UNIQUE constraint
CREATE INDEX IDX_PRES_PAT_NUMBER ON HIS_PRESCRIPTIONS(PRES_PAT_NUMBER);
CREATE INDEX IDX_PRES_DOC_NUMBER ON HIS_PRESCRIPTIONS(PRES_DOC_NUMBER);
CREATE INDEX IDX_LAB_PAT_NUMBER ON HIS_LABORATORY(LAB_PAT_NUMBER);
CREATE INDEX IDX_LAB_DOC_NUMBER ON HIS_LABORATORY(LAB_DOC_NUMBER);
CREATE INDEX IDX_VIT_PAT_NUMBER ON HIS_VITALS(VIT_PAT_NUMBER);
CREATE INDEX IDX_SURG_PAT_NUMBER ON HIS_SURGERY(SURG_PAT_NUMBER);
-- CREATE INDEX IDX_USER_EMAIL ON HIS_USERS(USER_EMAIL); -- Already indexed via UNIQUE constraint

-- ============================================
-- SECTION 7: ROLE-BASED VIEWS (OPTIONAL)
-- ============================================
-- Note: Creating views requires CREATE VIEW privilege
-- If you get ORA-01031 error, ask DBA to grant: GRANT CREATE VIEW TO your_username;
-- For now, these are commented out. Uncomment after getting privilege.

/*
-- View for Doctors to see their assigned patients
CREATE OR REPLACE VIEW V_DOCTOR_PATIENTS AS
SELECT 
    d.DOC_NUMBER,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS Doctor_Name,
    d.DOC_DEPT,
    p.PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS Patient_Name,
    p.PAT_AGE,
    p.PAT_PHONE,
    p.PAT_TYPE,
    p.PAT_AILMENT,
    p.PAT_DATE_JOINED
FROM HIS_DOCS d
INNER JOIN HIS_PATIENTS p ON d.DOC_NUMBER = p.PAT_ASSIGNED_DOC
WHERE d.DOC_STATUS = 'Active';

-- View for Patients to see their prescriptions
CREATE OR REPLACE VIEW V_PATIENT_PRESCRIPTIONS AS
SELECT 
    p.PAT_NUMBER,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS Patient_Name,
    pr.PRES_NUMBER,
    pr.PRES_DATE,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS Prescribed_By_Doctor,
    d.DOC_DEPT,
    pr.PRES_MEDICATION,
    pr.PRES_DOSAGE,
    pr.PRES_FREQUENCY,
    pr.PRES_NOTES AS Prescription_Notes,
    pr.PRES_STATUS
FROM HIS_PATIENTS p
INNER JOIN HIS_PRESCRIPTIONS pr ON p.PAT_NUMBER = pr.PRES_PAT_NUMBER
LEFT JOIN HIS_DOCS d ON pr.PRES_DOC_NUMBER = d.DOC_NUMBER;
*/

COMMIT;

-- ============================================
-- SECTION 8: DATA VALIDATION AND INTEGRITY
-- ============================================

-- Update trigger to set UPDATED_AT timestamp
CREATE OR REPLACE TRIGGER HIS_ADMIN_UPDATE_TRG
BEFORE UPDATE ON HIS_ADMIN
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER HIS_DOCS_UPDATE_TRG
BEFORE UPDATE ON HIS_DOCS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER HIS_PATIENTS_UPDATE_TRG
BEFORE UPDATE ON HIS_PATIENTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER HIS_PHARM_UPDATE_TRG
BEFORE UPDATE ON HIS_PHARMACEUTICALS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- ============================================
-- SECTION 9: DATABASE SUMMARY
-- ============================================

SELECT 'Schema SCHEMA_PROJECT created successfully!' AS Status FROM DUAL;
SELECT '20 Core Tables with full normalization (3NF)' AS Info FROM DUAL;
SELECT 'All constraints, foreign keys, and triggers implemented' AS Info FROM DUAL;
SELECT 'Ready for data insertion!' AS Info FROM DUAL;

-- Show table count
SELECT COUNT(*) AS Total_Tables 
FROM user_tables 
WHERE table_name LIKE 'HIS_%';

-- Show sequence count
SELECT COUNT(*) AS Total_Sequences 
FROM user_sequences 
WHERE sequence_name LIKE 'HIS_%';

-- Show constraint count
SELECT COUNT(*) AS Total_Constraints
FROM user_constraints
WHERE table_name LIKE 'HIS_%';

-- Show foreign key relationships
SELECT 
    a.table_name AS Child_Table,
    a.constraint_name AS FK_Name,
    b.table_name AS Parent_Table
FROM user_constraints a
JOIN user_constraints b ON a.r_constraint_name = b.constraint_name
WHERE a.constraint_type = 'R'
AND a.table_name LIKE 'HIS_%'
ORDER BY a.table_name;

COMMIT;
