-- ============================================
-- UPDATE PATIENT TRANSFER VIEW
-- Purpose: Add doctor name for PT_AUTHORIZED_BY field
-- ============================================

CREATE OR REPLACE VIEW V_PATIENT_TRANSFER AS
SELECT 
    t.*,
    p.PAT_FNAME || ' ' || p.PAT_LNAME AS PT_PAT_NAME,
    p.PAT_EMAIL AS PT_PAT_EMAIL,
    p.PAT_PHONE AS PT_PAT_PHONE,
    p.PAT_TYPE AS PT_PAT_TYPE,
    d.DOC_FNAME || ' ' || d.DOC_LNAME AS PT_AUTHORIZED_DOC_NAME,
    d.DOC_EMAIL AS PT_AUTHORIZED_DOC_EMAIL
FROM HIS_PATIENT_TRANSFER t
LEFT JOIN HIS_PATIENTS p ON t.PT_PAT_NUMBER = p.PAT_NUMBER
LEFT JOIN HIS_DOCS d ON t.PT_AUTHORIZED_BY = d.DOC_NUMBER;

COMMIT;

-- Verify the view
SELECT PT_PAT_NAME, PT_AUTHORIZED_BY, PT_AUTHORIZED_DOC_NAME 
FROM V_PATIENT_TRANSFER 
WHERE ROWNUM <= 5;
